### PR TITLE
feat: fix overscroll background color

### PR DESCRIPTION
**Pull request by leonardodino**
really nice project guys! 😄 🎉 
congrats!

### CODE REVIEW

**Comment by tilmx** [comment]
First of all, thank you so much for contributing @leonardodino! 
I just try to understand what you mean with fixing the overscroll background color. Could you explain it shortly? Thanks!

**Comment by leonardodino** [comment]
on macOS and iOS when you scroll past the `<body>` you see the `<html>`'s background color:



This commit makes that white background the same color as the header's (:

**Comment by tilmx** [comment]
Ah, now I get it @leonardodino. Awesome. Makes completely sense to set the page background to the dark black.
One thing I came across when checking it out: Behind the application image below the hero, there is now a white background instead of a black background on the top (the image section has an &:after element that is now hidden because of z-index). Could you fix that (and if you could rebase the branch from master, that would be great! 🚀 ) 
Thank you very much!

# Branch layout:
bildschirmfoto 2017-12-23 um 19 11 38

# Intended layout:
bildschirmfoto 2017-12-23 um 19 11 46

**Comment by marionebl** [comment]
Deploy preview processing.

Built with commit 899077c41796d52ac78dc9b2a4091b26ac6ce016

https://app.netlify.com/sites/determined-cray-3fd905/deploys/5a3ec809a1147742a50fd475

**Comment by leonardodino** [comment]
oops, my bad! just rebased and fixed it

BTW: spaces vs tabs. choose one. 😝
zalgo

<sub>put an [.editorconfig](http://editorconfig.org/) in the root of the project</sub>

**Review by tilmx — APPROVED** [review]

**Comment by tilmx** [comment]
@leonardodino Thank you so much for contributing!
We are currently refactoring the LESS-files, so the spaces should disappear and be replaced by tabs 🚀

**Pull request merged**
